/* All creative work, jobs, credits, and exports here are simulated in memory. */
(() => {
  'use strict';
  const $ = s => document.querySelector(s);
  const esc = s => String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const mark = '<svg aria-hidden="true"><use href="#pig"/></svg>';
  const arrow = '<svg aria-hidden="true"><use href="#arrow"/></svg>';
  const steps = ['Bring a spark','Find the world','Shape scenes','Generate','Choose takes','Export'];
  const titles = ['Start with what you have.','Give the feeling a world.','Make every scene yours.','Ready when you are.','Keep the take that hits.','One film. All your decisions.'];
  const sceneSeeds = [
    {id:1,title:'The last wash',prompt:'A little green clay frog sits alone on a washing machine. Empty chairs, pink neon. Push in slowly as the city falls asleep.',camera:'Slow push in',framing:'Medium wide'},
    {id:2,title:'A small universe',prompt:'Close on the same frog as soap bubbles float past. Neon reflections in its eyes. One bubble holds a tiny, impossible galaxy.',camera:'Gentle orbit',framing:'Close-up'},
    {id:3,title:'First light',prompt:'The same frog sits on a rooftop at dawn, holding a tiny flower. A warm breeze. For the first time, a little hope.',camera:'Slow pull back',framing:'Wide'}
  ];
  const fresh = () => ({stage:2,selected:1,format:'16:9',quality:'2K',pacing:'Music video',style:'Tactile clay / neon after hours',idea:'A heartbreak song at 2 a.m. A lonely clay frog. A laundromat that feels like the last place awake. End with a little hope.',audio:'Midnight spin.wav',refs:['Leading frog.webp'],duration:30,scenes:sceneSeeds.map(s=>({...s,seconds:10,sync:'Off',status:'draft',takes:[],active:0})),revision:1,exportRevision:0,exporting:false,exportProgress:0,generated:false,spent:0,chatNotes:[],saved:'All changes saved in this preview',captions:false,composerDraft:''});
  let state=fresh(), tour=-1, touring=false, tourTimer, jobs=[], tourJobs=[], playbackTimer, playing=false, playhead=0;
  const scopes = [$('#studio'),$('#director')];
  const selected=()=>state.scenes.find(s=>s.id===state.selected)||state.scenes[0];
  const total=()=>state.scenes.reduce((n,s)=>n+s.seconds,0);
  const stamp=n=>`${Math.floor(n/60).toString().padStart(2,'0')}:${Math.floor(n%60).toString().padStart(2,'0')}`;
  const rate=()=>state.quality==='2K'?40:30;
  const quote=()=>state.scenes.filter(s=>!s.takes.length).length*rate();
  const inProgress=()=>state.scenes.some(s=>s.status==='generating'||s.status==='queued');
  const ready=()=>state.scenes.every(s=>s.takes.length>0);
  const button=(label,action,primary=false,extra='')=>`<button class="sc-button ${primary?'sc-primary':''}" data-action="${action}" ${extra}>${label}</button>`;
  const opts=(items,current)=>items.map(s=>`<option ${s===current?'selected':''}>${esc(s)}</option>`).join('');
  const select=(label,key,items,value)=>`<label class="sc-field">${label}<select data-field="${key}">${opts(items,value)}</select></label>`;
  const wave=(n=48)=>`<div class="sc-wave">${Array.from({length:n},(_,i)=>`<i style="height:${6+(i*17)%27}px"></i>`).join('')}</div>`;
  const art=(s,extra='')=>`<div class="sc-art sc-shot-${s.id-1} ${extra}" role="img" aria-label="${esc(s.title)} — clay frog storyboard still"></div>`;
  const status=s=>s.status==='generating'?'Generating…':s.status==='queued'?'Queued':s.takes.length?`Take ${s.active} selected`:'Draft';
  const tourSteps=[
    {stage:0,title:'01 / Bring your spark',text:'Add the song and character once. Choose the canvas. These assets follow the project into both views.',focus:'intake'},
    {stage:1,title:'02 / Set the direction',text:'Describe the feeling. Pick pacing and a visual style before planning individual scenes.',focus:'direction'},
    {stage:2,title:'03 / Direct a scene',text:'Select scene 2. Its prompt, framing, camera move, and lip sync controls open together.',focus:'inspector'},
    {stage:2,title:'04 / Make a precise change',text:'Switch to a locked camera. Only scene 2 changes; the other scenes keep their direction.',focus:'inspector'},
    {stage:3,title:'05 / Review the cost',text:'See the selected scenes, resolution, and total together. Generation starts only after this decision.',focus:'generation'},
    {stage:3,title:'06 / Follow the run',text:'Each scene moves from queued to generating to ready. Switching views keeps this same run.',focus:'generation'},
    {stage:4,title:'07 / Choose your take',text:'Try a warmer take for scene 2. Compare it with the original, then choose which one enters the cut.',focus:'takes'},
    {stage:5,title:'08 / Assemble the cut',text:'Assemble the chosen takes with the full audio. The export has its own visible progress.',focus:'export'},
    {stage:5,title:'09 / Take it with you',text:'The film is ready. In this prototype, play the animated storyboard or download the actual shot list.',focus:'export'}
  ];
  function touch(note='Changes saved to this scene'){state.revision++;state.saved=note;}
  function header(mode){return `<header class="sc-header"><a href="#splash" class="sc-wordmark" aria-label="Slopcannon home">${mark}<span>SLOPCANNON</span></a><div class="sc-project-name">Midnight spin <small><span class="sc-green-dot"></span> ${ready()?'Clips ready':'In development'} · ${stamp(total())}</small></div><div class="sc-mode-switch" aria-label="Working mode"><a href="#studio" class="${mode==='studio'?'is-active':''}">Studio</a><a href="#director" class="${mode==='director'?'is-active':''}">Chat + controls</a></div><span class="sc-demo-badge">INTERACTIVE DEMO</span></header>`;}
  function tourBar(){const t=tourSteps[tour];return `<div class="sc-tour ${tour>=0?'sc-tour-active':''}"><div class="sc-tour-copy"><span class="sc-tour-label">${t?t.title:'A WHOLE FILM. EVERY LITTLE DECISION.'}</span><p>${t?t.text:'Take the guided tour, or click around and direct it yourself. All generation and credit amounts are simulated.'}</p></div><div class="sc-tour-actions">${tour<0?button('▶ Play walkthrough','tour-start',true):`${button('←','tour-back',false,'aria-label="Previous walkthrough step" '+(tour===0?'disabled':''))}${button(touring?'Ⅱ Pause':'▶ Auto','tour-play')}${button(tour===8?'Done':'Next →','tour-next',true)}`}<button class="sc-icon-button" data-action="reset" title="Reset demo" aria-label="Reset demo">↺</button></div>${t?`<div class="sc-tour-progress"><i style="width:${(tour+1)/9*100}%"></i></div>`:''}</div>`;}
  function stageNav(){return `<nav class="sc-stage-nav" aria-label="Film workflow">${steps.map((s,i)=>`<button data-stage="${i}" class="${state.stage===i?'is-current':''}" ${state.stage===i?'aria-current="step"':''}><span>${i+1}</span>${s}</button>`).join('')}</nav>`;}
  function library(){return `<aside class="sc-library"><div class="sc-kicker">PROJECT ASSETS</div><button class="sc-audio-card" data-action="audio"><span>♫</span><strong>${esc(state.audio)}</strong><small>${stamp(total())} · ${state.audio==='Midnight spin.wav'?'Sample audio':'Local filename only'}</small>${wave(30)}</button><div class="sc-ref-card">${art(state.scenes.find(s=>s.id===1))}<strong>Our leading frog</strong><small>Character reference</small></div>${state.refs.filter(r=>r!=='Leading frog.webp').map(r=>`<div class="sc-file-name">${esc(r)}</div>`).join('')}<button class="sc-add-reference" data-action="refs">+ Add reference</button><div class="sc-library-notes"><div class="sc-kicker">THE FEELING</div><p>Tactile clay.<br>A long night.<br>A little hope.</p><span class="sc-library-credit">${state.spent} demo credits used</span></div><a class="sc-brand-link" href="#brand">${mark} Explore the snout ↗</a></aside>`;}
  function player(compact=false){const s=selected();return `<div class="sc-player ${compact?'is-compact':''} ${playing?'is-playing':''}" data-format="${state.format}">${art(s,s.active>1?'sc-take-warm':'')}<div class="sc-player-top"><span>0${s.id} · ${esc(s.title)}</span><span>${state.format} / ${state.quality}</span></div><div class="sc-player-center" aria-hidden="true">${s.status==='generating'?'<span class="sc-loader"></span>':''}</div><div class="sc-player-bottom"><button class="sc-play" data-action="play" aria-label="${playing?'Pause':'Play'} animated storyboard">${playing?'Ⅱ':'▶'}</button><span class="sc-time">${stamp(playhead)} <span class="sc-muted">/ ${stamp(total())}</span></span><span class="sc-player-caption">SILENT ANIMATED STORYBOARD</span></div><div class="sc-playhead"><i style="width:${playhead/total()*100}%"></i></div></div>`;}
  function timeline(){let n=0;return `<section class="sc-timeline"><div class="sc-timeline-heading"><strong>The sequence</strong><span>${state.scenes.length} scenes · ${total()} seconds</span></div><div class="sc-scene-strip">${state.scenes.map(s=>{const start=n;n+=s.seconds;return `<button class="sc-scene-tile ${s.id===state.selected?'is-selected':''}" data-scene="${s.id}" aria-label="Select scene ${s.id}: ${esc(s.title)}" aria-pressed="${s.id===state.selected}">${art(s,s.active>1?'sc-take-warm':'')}<span>0${s.id} <b>${esc(s.title)}</b></span><small>${stamp(start)} — ${stamp(n)}</small><div class="sc-scene-status ${s.takes.length?'is-ready':''}">${s.takes.length?'✓ ':''}${status(s)}</div></button>`}).join('')}</div><div class="sc-audio-track"><span>♫ ${esc(state.audio)}</span>${wave(80)}<span>${stamp(total())}</span></div></section>`;}
  function inspector(inline=false){const s=selected();return `<section class="sc-inspector ${inline?'sc-inline-inspector':''}" data-focus="inspector"><div class="sc-inspector-heading"><div><div class="sc-kicker">SCENE 0${s.id} / DIRECTION</div><h2>${esc(s.title)}</h2></div>${inline?`<span class="sc-tag">${s.seconds}s</span>`:''}</div><label class="sc-field">Scene direction<textarea rows="4" data-field="prompt">${esc(s.prompt)}</textarea></label><div class="sc-field-grid">${select('Camera move','camera',['Slow push in','Gentle orbit','Slow pull back','Locked off','Handheld'],s.camera)}${select('Framing','framing',['Medium wide','Close-up','Wide','Extreme close-up'],s.framing)}${select('Lip sync','sync',['Off','Auto','Required'],s.sync)}<label class="sc-field">Duration <span class="sc-unit">seconds</span><input type="number" data-field="seconds" value="${s.seconds}" min="4" max="20"></label></div><div class="sc-reference-inline">${mark}<div>Leading frog<small>Same character across every scene</small></div><span>✓</span></div><div class="sc-save-note">● ${esc(state.saved)}</div>${!inline?`<div class="sc-scene-order"><span>Scene order</span>${button('←','move-left',false,'aria-label="Move scene earlier" '+(state.scenes[0].id===s.id?'disabled':''))}${button('→','move-right',false,'aria-label="Move scene later" '+(state.scenes.at(-1).id===s.id?'disabled':''))}</div>`:''}${state.stage<3?button('Review generation '+arrow,'to-generate',true):''}</section>`;}
  function intake(){return `<section class="sc-intake sc-flow-card" data-focus="intake"><div class="sc-intake-assets"><button class="sc-dropzone" data-action="audio"><span class="sc-upload-symbol">♫</span><strong>${esc(state.audio)}</strong><small>Sample loaded · click to choose your audio</small>${wave(40)}</button><button class="sc-dropzone sc-image-drop" data-action="refs">${art(state.scenes.find(s=>s.id===1))}<div><strong>Your leading character</strong><small>${state.refs.length} reference${state.refs.length>1?'s':''} · add more +</small></div></button></div><label class="sc-field">What’s the idea?<textarea rows="3" data-field="idea">${esc(state.idea)}</textarea></label><div class="sc-horizontal-field"><span>Your canvas</span><div class="sc-choice-group">${['16:9','9:16','1:1'].map(v=>`<button data-format="${v}" class="${v===state.format?'is-picked':''}"><i style="aspect-ratio:${v.replace(':','/')}"></i>${v}</button>`).join('')}</div></div><div class="sc-action-row"><span class="sc-muted">Files stay in your browser for this demo.</span>${button('Build direction '+arrow,'to-direction',true)}</div></section>`;}
  function direction(){return `<section class="sc-flow-card sc-direction" data-focus="direction"><div class="sc-mood-triptych">${state.scenes.map(s=>art(s)).join('')}<span>THE WORLD / MIDNIGHT SPIN</span></div><h2>Lonely doesn’t have to look empty.</h2><p>Begin in the last laundromat awake. Let the chorus turn soap bubbles into a small universe. Find daylight in the final shot.</p><label class="sc-field">Visual style<input data-field="style" value="${esc(state.style)}"></label><div class="sc-horizontal-field"><span>Pacing</span><div class="sc-choice-group">${['Long takes','Music video','Rapid fire'].map(p=>`<button class="${p===state.pacing?'is-picked':''}" data-pacing="${p}">${p}</button>`).join('')}</div></div><div class="sc-continuity"><span>↔</span><div><strong>One character. One world.</strong><small>Green clay, purple jacket, handmade texture. Keep these details across all three scenes.</small></div></div><div class="sc-action-row"><span class="sc-muted">${esc(state.format)} · ${esc(state.pacing)}</span>${button('Plan scenes '+arrow,'to-scenes',true)}</div></section>`;}
  function genCard(){const generating=inProgress();return `<section class="sc-flow-card sc-generation" data-focus="generation"><div class="sc-card-eyebrow">${ready()?'THE CLIPS ARE IN':generating?'THE CANNON IS WORKING':'LET’S MAKE THE CLIPS'}</div><h2>${ready()?'Three moments, ready for your eye.':generating?'Your world is taking shape.':'A clear plan. A clear cost.'}</h2><div class="sc-run-settings">${select('Resolution','quality',['2K','1080p'],state.quality).replace('<select',`<select ${generating||ready()?'disabled':''}`)}<div><span>Format</span><strong>${state.format}</strong></div><div><span>Length</span><strong>${stamp(total())}</strong></div></div><div class="sc-job-list">${state.scenes.map(s=>`<div class="sc-job">${art(s)}<div><strong>0${s.id} · ${esc(s.title)}</strong><small>${s.seconds}s · ${esc(s.camera)}</small></div><span class="sc-job-status ${s.takes.length?'is-ready':''}">${status(s)}</span>${s.status==='generating'?'<div class="sc-job-progress"><i></i></div>':''}</div>`).join('')}</div><div class="sc-cost"><span>${ready()?'This run':'Estimated generation'}<small>Illustrative credits for this prototype</small></span><strong>${ready()?state.spent:quote()} <small>credits</small></strong></div><div class="sc-action-row"><span class="sc-muted">${generating?'You can switch views while this runs.':ready()?'Your takes are preserved in both views.':'Only starts when you choose Generate.'}</span>${button(generating?'Generating…':ready()?'Review takes →':`Generate ${state.scenes.filter(s=>!s.takes.length).length} scenes →`,ready()?'to-review':'generate',true,generating?'disabled':'')}</div></section>`;}
  function takes(){const s=selected();if(!s.takes.length)return `<section class="sc-flow-card" data-focus="takes"><h2>The best take starts with a first take.</h2><p>Generate your scenes, then compare versions here.</p>${button('Review generation →','to-generate',true)}</section>`;return `<section class="sc-flow-card sc-takes" data-focus="takes"><div class="sc-timeline-heading"><strong>Scene 0${s.id} · Choose a take</strong><span>${s.takes.length} version${s.takes.length>1?'s':''}</span></div><div class="sc-take-grid">${s.takes.map(t=>`<button data-take="${t}" class="sc-take ${s.active===t?'is-selected':''}">${art(s,t>1?'sc-take-warm':'')}<span><b>Take ${t}</b><small>${t>1?'Warmer / more intimate':'Original direction'}</small></span><em>${s.active===t?'✓ In the cut':'Use this take'}</em></button>`).join('')}</div><div class="sc-reroll"><label class="sc-field">Direction for the next take<input data-field="reroll" value="${esc(s.reroll||'Warmer light. A quieter, more intimate moment.')}" placeholder="What should change?"></label>${button(s.status==='generating'?'Making a new take…':`Try another take · ${rate()} credits`,'reroll',false,s.status==='generating'?'disabled':'')}</div><p class="sc-muted">Demo: the new take previews a warmer grade. Your original stays available.</p><div class="sc-action-row"><span class="sc-muted">Only this scene gets a new take.</span>${button('Prepare export '+arrow,'to-export',true,!ready()?'disabled':'')}</div></section>`;}
  function exportCard(){const done=state.exportRevision===state.revision,stale=state.exportRevision>0&&!done;return `<section class="sc-flow-card sc-export" data-focus="export"><div class="sc-export-mark ${state.exporting?'is-working':''}">${mark}</div><div class="sc-card-eyebrow">${done?'YOUR CUT IS READY':state.exporting?'PUTTING IT ALL TOGETHER':stale?'THE CUT HAS CHANGED':'THE LAST STEP'}</div><h2>${done?'Made it yours.':state.exporting?'One film, coming together.':stale?'A new cut deserves a new export.':'Bring the whole thing home.'}</h2><div class="sc-export-details"><span>${stamp(total())}<small>Full timeline</small></span><span>${state.quality}<small>${state.format} canvas</small></span><span>MP4<small>Product export format</small></span></div><div class="sc-selected-takes">${state.scenes.map(s=>`<span>Scene ${s.id} <b>${s.active?'Take '+s.active:'Not generated'}</b></span>`).join('')}</div><label class="sc-check"><input type="checkbox" data-field="captions" ${state.captions?'checked':''}> Include captions</label>${state.exporting?`<div class="sc-assembly-progress" role="progressbar" aria-label="Simulated assembly" aria-valuenow="${state.exportProgress}" aria-valuemin="0" aria-valuemax="100"><i style="width:${state.exportProgress}%"></i></div><p class="sc-muted">${state.exportProgress<35?'Preparing selected takes':state.exportProgress<80?'Joining the sequence and audio':'Finishing the export'} · ${state.exportProgress}%</p>`:done?`<div class="sc-export-actions">${button('▶ Play storyboard','play',true)}${button('Download shot list ↓','download')}</div><p class="sc-muted">Prototype complete. Playback is a silent animated storyboard; a real generation would download your MP4 here.</p>`:`${button(ready()?(stale?'Assemble updated cut →':'Assemble video →'):'Generate scenes first',ready()?'assemble':'to-generate',true)}<p class="sc-muted">${ready()?'Assembly uses your selected takes and full audio.':'Your scene choices stay here while the clips generate.'}</p>`}</section>`;}
  function stageBody(){return state.stage===0?intake():state.stage===1?direction():state.stage===2?player()+timeline():state.stage===3?genCard()+timeline():state.stage===4?player()+takes()+timeline():exportCard()+(state.exportRevision?player(true):'')+timeline();}
  function projectInspector(){return `<aside class="sc-inspector sc-project-inspector"><div class="sc-kicker">THE PRODUCTION BRIEF</div><h2>Room for your vision.</h2><p class="sc-muted">Set the world first. The scene controls arrive when you plan the sequence.</p><div class="sc-reference-inline">${mark}<div>Music video<small>One song. One continuous story.</small></div></div><div style="margin-top:23px">${select('Resolution','quality',['2K','1080p'],state.quality)}</div><div class="sc-context-stats"><span>Canvas <b>${state.format}</b></span><span>Full audio <b>${stamp(total())}</b></span><span>Character <b>Leading frog</b></span><span>Pacing <b>${esc(state.pacing)}</b></span></div><div class="sc-save-note">● References stay with the project</div></aside>`;}
  function studio(){return `<div class="sc-workbench">${header('studio')}${tourBar()}${stageNav()}<div class="sc-shell">${library()}<main class="sc-main"><div class="sc-stage-title"><div><div class="sc-kicker">0${state.stage+1} / ${steps[state.stage].toUpperCase()}</div><h1>${titles[state.stage]}</h1></div><span class="sc-tag">${state.stage>2?'LIVE PROJECT':'DRAFT 01'}</span></div>${stageBody()}</main>${state.stage<2?projectInspector():inspector()}</div><div class="sc-workspace-foot"><span>● ${esc(state.saved)}</span><span>Same film in Studio and Chat + controls</span></div></div>`;}
  function directorContext(){return `<aside class="sc-director-context"><div class="sc-context-head"><span>THE FILM, AT A GLANCE</span><a href="#studio">Open Studio ↗</a></div>${player(true)}<div class="sc-context-meta"><strong>Midnight spin</strong><span>${state.format} · ${state.quality} · ${stamp(total())}</span></div><div class="sc-context-scenes">${state.scenes.map(s=>`<button data-scene="${s.id}" class="${state.selected===s.id?'is-selected':''}">${art(s)}<div><strong>0${s.id} ${esc(s.title)}</strong><small>${s.takes.length?status(s):s.camera}</small></div><span>${s.takes.length?'✓':'↗'}</span></button>`).join('')}</div><div class="sc-context-stats"><span>Selected scene <b>0${state.selected}</b></span><span>Demo spend <b>${state.spent} credits</b></span><span>Export <b>${state.exportRevision===state.revision?'Ready':state.exportRevision?'Needs update':'Not assembled'}</b></span></div><div class="sc-producer-note">${mark}<p>Talk it through.<br>Touch the controls.<br>Keep the same film.</p></div></aside>`;}
  const userWords=['I’ve got a song and this little clay frog. Make it lonely, strange, and beautiful.','A laundromat at 2 a.m. A little heartbreak, a little hope.','Keep the camera still in scene 2. I want the bubbles to do the moving.','Let’s see the cost before we make the clips.','Scene 2 could feel warmer. Let’s try one more take.','These are the takes. Bring it all together.'];
  const producerWords=['Let’s start with your song and character. Set the canvas here; I’ll carry the references through every scene.','Let’s give the night an arc: solitude, a little surrealism, then the first sign of morning.','Here’s the scene, with the controls right where we’re talking. Change one detail or direct the whole shot.','Here’s the complete run. Your scene plan, quality, and cost are in one place before you start.','Your original stays in the cut until you choose another take. Let’s make the change specific.','The scene choices are set. Assemble the selected takes with the full audio, then take the film with you.'];
  function chatBody(){return state.stage===0?intake():state.stage===1?direction():state.stage===2?`<div class="sc-chat-scene-card"><div class="sc-chat-scene-preview">${art(selected())}<span>SCENE 0${selected().id} / ${esc(selected().title)}</span></div>${inspector(true)}</div><div class="sc-chat-quick">${button('Lock the camera','lock-camera')}${button('Make it more intimate','intimate')}${button('Next scene →','next-scene')}</div>`:state.stage===3?genCard():state.stage===4?takes():exportCard();}
  function director(){return `<div class="sc-workbench sc-director">${header('director')}${tourBar()}${stageNav()}<div class="sc-director-shell"><main class="sc-conversation"><div class="sc-chat-chapter"><span>YOUR PRODUCER / MIDNIGHT SPIN</span><span>0${state.stage+1} — ${steps[state.stage]}</span></div><div class="sc-user-message">${userWords[state.stage]}</div><article class="sc-producer-message"><div class="sc-producer-author">${mark}<strong>Your Producer</strong><span>DEMO</span></div><p>${producerWords[state.stage]}</p>${chatBody()}</article>${state.chatNotes.filter(n=>n.stage===state.stage).map(n=>`<div class="sc-user-message">${esc(n.text)}</div><article class="sc-producer-message"><div class="sc-producer-author">${mark}<strong>Your Producer</strong><span>DEMO</span></div><p>${esc(n.reply)}</p></article>`).join('')}<form class="sc-chat-composer"><label class="sr-only" for="sc-chat-prompt">Direction for your Producer</label><textarea id="sc-chat-prompt" rows="2" placeholder="Tell me what to change in scene ${state.selected}…">${esc(state.composerDraft)}</textarea><div><span>Applies to scene ${state.selected} · scripted demo</span><button type="submit" class="sc-send" aria-label="Send direction">↑</button></div></form><p class="sc-chat-disclaimer">Same scene controls. Same takes. One conversation.</p></main>${directorContext()}</div></div>`;}
  function render(){
    const active=document.activeElement,root=active?.closest('#studio,#director');
    const identity=active?.id?['id',active.id]:['field','action','stage','scene','take'].map(k=>[k,active?.dataset?.[k]]).find(([,v])=>v!==undefined);
    const savedFocus=root&&identity?{root:root.id,key:identity[0],value:identity[1],tag:active.tagName,start:active.selectionStart,end:active.selectionEnd}:null;
    scopes[0].innerHTML=studio();scopes[1].innerHTML=director();
    if(tour>=0)document.querySelectorAll(`[data-focus="${tourSteps[tour].focus}"]`).forEach(el=>el.classList.add('sc-spotlight'));
    if(savedFocus){const r=document.getElementById(savedFocus.root);const el=savedFocus.key==='id'?document.getElementById(savedFocus.value):r.querySelector(`${savedFocus.tag}[data-${savedFocus.key}="${savedFocus.value}"]`);if(el&&r.classList.contains('active')){el.focus({preventScroll:true});if(typeof savedFocus.start==='number'&&el.setSelectionRange)try{el.setSelectionRange(savedFocus.start,savedFocus.end)}catch{}}}
  }
  function clearJobs(){jobs.forEach(clearTimeout);jobs=[];}
  function later(fn,ms){jobs.push(setTimeout(fn,ms));}
  function stopPlay(){clearInterval(playbackTimer);playing=false;}
  function switchStage(stage){state.stage=Math.max(0,Math.min(5,Number(stage)));stopPlay();render();}
  function pauseTour(){touring=false;clearTimeout(tourTimer);tourJobs.forEach(clearTimeout);tourJobs=[];document.querySelectorAll('[data-action="tour-play"]').forEach(b=>b.textContent='▶ Auto');}
  function markReady(){state.scenes.forEach(s=>{if(!s.takes.length){s.takes=[1];s.active=1;}s.status='ready'});state.generated=true;}
  function generate(){if(inProgress()||ready())return;state.stage=3;state.spent+=quote();state.scenes.forEach(s=>{if(!s.takes.length)s.status='queued'});state.saved='One shared run · visible in Studio and chat';render();state.scenes.filter(s=>!s.takes.length).forEach((s,i)=>{later(()=>{s.status='generating';render()},300+i*650);later(()=>{s.status='ready';s.takes=[1];s.active=1;state.generated=ready();touch('Your clips are ready to review');render()},1900+i*650)});}
  function reroll(){const s=selected();if(s.status==='generating'||!s.takes.length)return;state.spent+=rate();s.status='generating';state.saved='Making one new take · original preserved';render();later(()=>{const take=s.takes.length+1;s.takes.push(take);s.status='ready';state.saved=`Scene ${s.id}: Take ${take} is ready to compare`;render()},1900);}
  function assemble(){if(!ready()||state.exporting)return;state.exporting=true;state.stage=5;const rev=state.revision;state.exportProgress=0;render();[15,42,73,94,100].forEach((p,i)=>later(()=>{state.exportProgress=p;if(p===100){state.exporting=false;state.exportRevision=rev;state.saved=rev===state.revision?'Your export is ready':'Cut changed during assembly · export again'}render()},500+i*600));}
  function playback(){if(playing){stopPlay();render();return;}if(playhead>=total())playhead=0;playing=true;render();playbackTimer=setInterval(()=>{playhead+=.25;let elapsed=0;let s=state.scenes.find(s=>{elapsed+=s.seconds;return playhead<elapsed})||state.scenes.at(-1);if(s.id!==state.selected){state.selected=s.id;render();}document.querySelectorAll('.sc-time').forEach(el=>el.innerHTML=`${stamp(playhead)} <span class="sc-muted">/ ${stamp(total())}</span>`);document.querySelectorAll('.sc-playhead i').forEach(el=>el.style.width=`${playhead/total()*100}%`);if(playhead>=total()){stopPlay();playhead=0;render()}},250);}
  function tourStep(n){
    clearJobs();tourJobs.forEach(clearTimeout);tourJobs=[];stopPlay();playhead=0;
    tour=Math.max(0,Math.min(8,n));state=fresh();state.stage=tourSteps[tour].stage;
    if(tour>=2)state.selected=2;
    if(tour>=3)selected().camera='Locked off';
    if(tour>=6){markReady();state.spent=120;}
    if(tour===5)generate();
    if(tour===6){const scene=selected();scene.reroll='Warmer light. A quieter, more intimate moment.';reroll();tourJobs.push(setTimeout(()=>{if(scene.takes.includes(2)){scene.active=2;touch('Scene 2 · Take 2 selected for the cut');render()}},2300));}
    if(tour>=7){selected().takes=[1,2];selected().active=2;state.spent=160;}
    if(tour===7)assemble();
    if(tour===8){state.exportRevision=state.revision;state.saved='Walkthrough complete · try your own decisions';}
    render();window.scrollTo({top:0,behavior:window.matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'});
    if(touring){clearTimeout(tourTimer);tourTimer=setTimeout(()=>{if(tour===8){pauseTour();render()}else tourStep(tour+1)},tour===5||tour===7?5200:4700);}
  }
  function exportPlan(){const data={title:'Midnight spin',concept:true,format:state.format,resolution:state.quality,audio:state.audio,visualStyle:state.style,scenes:state.scenes.map(s=>({scene:s.id,title:s.title,durationSeconds:s.seconds,direction:s.prompt,camera:s.camera,framing:s.framing,lipSync:s.sync,selectedTake:s.active})),note:'Slopcannon interactive design prototype. No real generation or charges.'};const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='midnight-spin-shot-list.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
  function handleAction(action){if(!action.startsWith('tour-'))pauseTour();switch(action){case 'reset':clearJobs();stopPlay();state=fresh();tour=-1;playhead=0;render();break;case 'audio':$('#sc-demo-audio').click();break;case 'refs':$('#sc-demo-refs').click();break;case 'to-direction':switchStage(1);break;case 'to-scenes':switchStage(2);break;case 'to-generate':switchStage(3);break;case 'to-review':switchStage(4);break;case 'to-export':switchStage(5);break;case 'generate':generate();break;case 'reroll':reroll();break;case 'assemble':assemble();break;case 'download':exportPlan();break;case 'play':playback();break;case 'lock-camera':selected().camera='Locked off';touch('Scene '+state.selected+' · camera locked');render();break;case 'intimate':selected().framing='Close-up';touch('Scene '+state.selected+' · close-up framing');render();break;case 'next-scene':state.selected=state.scenes[(state.scenes.findIndex(s=>s.id===state.selected)+1)%3].id;render();break;case 'move-left':case 'move-right':{const i=state.scenes.findIndex(s=>s.id===state.selected),j=i+(action==='move-left'?-1:1);if(j>=0&&j<state.scenes.length){[state.scenes[i],state.scenes[j]]=[state.scenes[j],state.scenes[i]];touch('Scene order updated');render();}break;}case 'tour-start':clearJobs();touring=true;tourStep(0);break;case 'tour-play':if(touring){pauseTour();render();}else{touring=true;tourStep(tour===8?0:tour);}break;case 'tour-back':pauseTour();tourStep(tour-1);break;case 'tour-next':pauseTour();if(tour===8){tour=-1;render()}else tourStep(tour+1);break;}}
  scopes.forEach(root=>{root.addEventListener('click',e=>{const action=e.target.closest('[data-action]');if(action){handleAction(action.dataset.action);return;}const step=e.target.closest('[data-stage]');if(step){pauseTour();tour=-1;switchStage(step.dataset.stage);return;}const scene=e.target.closest('[data-scene]');if(scene){pauseTour();stopPlay();state.selected=Number(scene.dataset.scene);playhead=state.scenes.slice(0,state.scenes.findIndex(s=>s.id===state.selected)).reduce((n,s)=>n+s.seconds,0);render();return;}const take=e.target.closest('[data-take]');if(take){pauseTour();selected().active=Number(take.dataset.take);touch('Scene '+state.selected+' · Take '+take.dataset.take+' selected');render();return;}const fmt=e.target.closest('[data-format]');if(fmt&&fmt.tagName==='BUTTON'){pauseTour();state.format=fmt.dataset.format;touch('Project canvas updated');render();}const pace=e.target.closest('[data-pacing]');if(pace){pauseTour();state.pacing=pace.dataset.pacing;touch('Project pacing updated');render();}});
    root.addEventListener('input',e=>{const key=e.target.dataset.field;if(e.target.matches('#sc-chat-prompt')){pauseTour();state.composerDraft=e.target.value;return;}if(!key||e.target.type==='checkbox'||e.target.tagName==='SELECT')return;pauseTour();if(['style','idea'].includes(key)){state[key]=e.target.value;}else if(key==='seconds'){selected().seconds=Math.max(4,Math.min(20,Number(e.target.value)||10));}else{selected()[key]=e.target.value;}touch('Scene '+state.selected+' · changes saved');});
    root.addEventListener('change',e=>{const key=e.target.dataset.field;if(!key)return;pauseTour();const value=e.target.value;if(['format','quality','style','idea','pacing'].includes(key)){state[key]=value;}else if(key==='captions'){state.captions=e.target.checked;}else if(key==='seconds'){selected().seconds=Math.max(4,Math.min(20,Number(value)||10));}else{selected()[key]=value;}touch(key==='idea'||key==='style'?'Project direction saved':'Scene '+state.selected+' · changes saved');render();});
    root.addEventListener('submit',e=>{if(!e.target.matches('.sc-chat-composer'))return;e.preventDefault();const input=e.target.querySelector('textarea'),text=input.value.trim();if(!text)return;pauseTour();let target=Number((text.match(/scene\s*(\d)/i)||[])[1]);if(target&&state.scenes.some(s=>s.id===target))state.selected=target;let s=selected(),reply='';if(/lock|still camera|static/i.test(text)){s.camera='Locked off';reply=`Scene ${s.id} now uses a locked camera. The other scenes keep their movement.`;}else if(/close|intimate/i.test(text)){s.framing='Close-up';reply=`Scene ${s.id} is now a close-up. The framing control and Studio inspector show the same choice.`;}else if(/lip.?sync/i.test(text)){s.sync=/off|no lip|without/i.test(text)?'Off':'Required';reply=`Scene ${s.id} lip sync is set to ${s.sync}.`;}else{s.prompt=text;reply=`Saved your direction to scene ${s.id}. This is a scripted prototype: your exact text is now in its Scene direction field.`;}state.chatNotes.push({stage:state.stage,text,reply});state.composerDraft='';touch(`Scene ${s.id} · direction updated from chat`);render();});});
  document.body.insertAdjacentHTML('beforeend','<input id="sc-demo-audio" type="file" accept="audio/*" hidden><input id="sc-demo-refs" type="file" accept="image/*" multiple hidden>');
  $('#sc-demo-audio').addEventListener('change',e=>{if(e.target.files[0]){state.audio=e.target.files[0].name;touch('Audio filename added locally · no upload');render();}e.target.value='';});
  $('#sc-demo-refs').addEventListener('change',e=>{state.refs.push(...[...e.target.files].map(f=>f.name));touch('Reference filenames added locally · no upload');render();e.target.value='';});
  window.addEventListener('hashchange',()=>{if(!['#studio','#director'].includes(location.hash)){pauseTour();stopPlay();}});
  render();
})();
